name: Laravel CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-versions: ['8.3']
        node-versions: ['20']

    name: PHP ${{ matrix.php-versions }} Test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, dom, fileinfo, mysql, gd, curl, zip, sqlite, pdo_sqlite
        coverage: none

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-versions }}-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --optimize-autoloader

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-versions }}

    - name: Cache NPM packages
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node-versions }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-versions }}-

    - name: Install NPM dependencies
      run: npm install

    - name: Build assets
      run: npm run build

    - name: Create environment file for testing
      run: |
        echo "APP_NAME=Laravel" > .env
        echo "APP_ENV=testing" >> .env
        echo "APP_KEY=" >> .env
        echo "APP_DEBUG=true" >> .env
        echo "APP_URL=http://localhost" >> .env
        echo "DB_CONNECTION=sqlite" >> .env
        echo "DB_DATABASE=:memory:" >> .env
        echo "SESSION_DRIVER=array" >> .env
        echo "CACHE_STORE=array" >> .env
        echo "QUEUE_CONNECTION=sync" >> .env
        echo "MAIL_MAILER=array" >> .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Clear config cache
      run: php artisan config:clear

    - name: Run database migrations
      run: php artisan migrate --force

    - name: Check code style (Laravel Pint)
      run: composer lint

    - name: Run static analysis (PHPStan)
      run: composer stan

    - name: Run tests
      run: php artisan test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results
        path: storage/logs/